/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[3];
new Text:Box;

//Textdraws
PublicTD[0] = TextDrawCreate(287.000000, 198.000000, "TextDraw");
TextDrawFont(PublicTD[0], 2);
TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[0], 352.500000, 17.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

Box = TextDrawCreate(216.000000, 182.000000, "a");
TextDrawFont(Box, 1);
TextDrawLetterSize(Box, 0.600000, 16.450122);
TextDrawTextSize(Box, 430.500000, 367.500000);
TextDrawSetOutline(Box, 0);
TextDrawSetShadow(Box, 0);
TextDrawAlignment(Box, 1);
TextDrawColor(Box, -256);
TextDrawBackgroundColor(Box, 255);
TextDrawBoxColor(Box, 155);
TextDrawUseBox(Box, 1);
TextDrawSetProportional(Box, 1);
TextDrawSetSelectable(Box, 0);

PublicTD[1] = TextDrawCreate(234.000000, 297.000000, "Aceitar");
TextDrawFont(PublicTD[1], 0);
TextDrawLetterSize(PublicTD[1], 0.612500, 2.000000);
TextDrawTextSize(PublicTD[1], 288.000000, 17.000000);
TextDrawSetOutline(PublicTD[1], 0);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], 9109759);
TextDrawBackgroundColor(PublicTD[1], 1433087999);
TextDrawBoxColor(PublicTD[1], 1433087794);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 1);

PublicTD[2] = TextDrawCreate(346.000000, 297.000000, "Cancelar");
TextDrawFont(PublicTD[2], 0);
TextDrawLetterSize(PublicTD[2], 0.612500, 2.000000);
TextDrawTextSize(PublicTD[2], 416.000000, 17.000000);
TextDrawSetOutline(PublicTD[2], 0);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -1962934017);
TextDrawBackgroundColor(PublicTD[2], -16776961);
TextDrawBoxColor(PublicTD[2], -16777166);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 1);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
