/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[1];
new Text:CidadeRPG;

//Textdraws
CidadeRPG = TextDrawCreate(279.000000, 414.000000, "CidadeRPG");
TextDrawFont(CidadeRPG, 0);
TextDrawLetterSize(CidadeRPG, 0.600000, 2.000000);
TextDrawTextSize(CidadeRPG, 221.500000, 17.000000);
TextDrawSetOutline(CidadeRPG, 0);
TextDrawSetShadow(CidadeRPG, 1);
TextDrawAlignment(CidadeRPG, 1);
TextDrawColor(CidadeRPG, -1);
TextDrawBackgroundColor(CidadeRPG, -1962934017);
TextDrawBoxColor(CidadeRPG, 50);
TextDrawUseBox(CidadeRPG, 0);
TextDrawSetProportional(CidadeRPG, 1);
TextDrawSetSelectable(CidadeRPG, 0);

PublicTD[0] = TextDrawCreate(280.000000, 428.000000, "www.cidaderpg.com");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.283333, 1.399999);
TextDrawTextSize(PublicTD[0], 221.000000, 27.500000);
TextDrawSetOutline(PublicTD[0], 0);
TextDrawSetShadow(PublicTD[0], 1);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 0);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
